apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: 038462753889.dkr.ecr.us-east-1.amazonaws.com/devsecops-petclinic
    newTag: latest